language: bash
services: docker

env:
  - VERSION=4.2
  - VERSION=4.7
  - VERSION=oaiprovider-4.7

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image='fcrepo4'

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
